src/com/itheima/vo/BirdVo.java
package com.itheima.vo;

import java.util.List;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.itheima.po.Bird;

public class BirdVo {

	private Bird bird;
	private String url;
	
	public Bird getBird() {
		return bird;
	}
	public void setBird(Bird bird) {
		this.bird = bird;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}

	@Override
	public String toString() {
		return "BirdVo [bird=" + bird + ", url=" + url + "]";
	}

	public List<BirdVo> transfer(List<Bird> birdList){
		return null;
	}
	
	/**
	 * 获取 对象的Json格式
	 * @param birdVo
	 * @return String
	 */
	public String getJson(BirdVo birdVo){
		ObjectMapper mapper = new ObjectMapper();
		String jsonString = null;
		try {
			jsonString = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(birdVo);
		} catch (JsonProcessingException e) {
			e.printStackTrace();
		}
		return jsonString;		
	}

}

src/com/itheima/controller/BirdController.java
package com.itheima.controller;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import com.itheima.dao.BirdMapper;
import com.itheima.po.Bird;
import com.itheima.service.BirdService;
import com.itheima.service.BirdServiceImpl;
/**
 * 控制器类
 */

public class BirdController implements Controller{
	@Override
	public ModelAndView handleRequest(HttpServletRequest request,
			               HttpServletResponse response)  {
		
	    ApplicationContext act = 
	            new ClassPathXmlApplicationContext("applicationContext.xml");
	    BirdService birdService = act.getBean(BirdService.class); 
	    
	    List<Bird> birdList = birdService.findBirdAll();
	    
         // 创建ModelAndView对象
		ModelAndView mav = new ModelAndView();
		
         // 向模型对象中添加数据
		mav.addObject("birdList", birdList);
         // 设置逻辑视图名
		mav.setViewName("/WEB-INF/jsp/bird.jsp");
         // 返回ModelAndView对象
		return mav;
	}
}

src/com/itheima/controller/BirdPageController.java
package com.itheima.controller;

import java.util.HashMap;
import java.util.List;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.itheima.po.Bird;
import com.itheima.service.BirdService;
import com.mysql.cj.xdevapi.JsonArray;

@Controller
public class BirdPageController {

	@RequestMapping("/birdpage")
	@ResponseBody
	public JSONArray getList() {
		
		ApplicationContext act = 
	            new ClassPathXmlApplicationContext("applicationContext.xml");
	    BirdService birdService = act.getBean(BirdService.class); 
	    
	    List<Bird> birdList = birdService.findBirdAll();
	    JSONArray array = JSONArray.parseArray(JSON.toJSONString(birdList));
		
		return array;
	}
	
}

src/com/itheima/controller/FirstController.java
package com.itheima.controller;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;
/**
 * 控制器类
 */
public class FirstController implements Controller{
	@Override
	public ModelAndView handleRequest(HttpServletRequest request,
			               HttpServletResponse response)  {
         // 创建ModelAndView对象
		ModelAndView mav = new ModelAndView();
         // 向模型对象中添加数据
		mav.addObject("msg", "这是我的第一个Spring MVC程序");
         // 设置逻辑视图名
		mav.setViewName("/WEB-INF/jsp/first.jsp");
         // 返回ModelAndView对象
		return mav;
	}
}

WebContent/WEB-INF/jsp/bird.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>鸟信息</title>
<link rel="stylesheet" type="text/css"
	href="https://www.layuicdn.com/layui-v2.5.6/css/layui.css" />

</head>
<body>
	<table class="layui-table">
		<colgroup>
			<col width="50">
			<col width="100">
		</colgroup>
		<thead>
			<tr>
				<th>编号</th>
				<th>名称</th>
			</tr>
		</thead>

		<tbody>
			<c:forEach items="${birdList}" var="bird" varStatus="status">
				<tr>
					<td>${bird.id}</td>
					<td>${bird.type}</td>
				</tr>
			</c:forEach>
		</tbody>
	</table>
	<script src="https://www.layuicdn.com/layui-v2.5.6/layui.js"></script>

</body>
<script type="text/javascript">
	console.log(${bird.list});
</script>
</html>

WebContent/WEB-INF/jsp/first.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 
     "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>入门程序</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- 引入 Bootstrap -->
<link
	href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
	rel="stylesheet">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

</head>
<head>
<body>
	<div class="container">
		<h1>${msg}</h1>
		<h2>添加Bootstrap 3支持</h2>

		<a
			href="https://www.runoob.com/bootstrap/bootstrap-environment-setup.html">菜鸟教程-Bootstrap3</a>
	</div>
</body>
</html>

WebContent/WEB-INF/jsp/first2.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <!-- import CSS -->
  <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
</head>
<body>
  <div id="app">
      <div><h2>{{message}}</h2></div>
  </div>

</body>
  <!-- import Vue before Element -->
  <script src="https://unpkg.com/vue/dist/vue.js"></script>
  <!-- import JavaScript -->
  <script src="https://unpkg.com/element-ui/lib/index.js"></script>
  <script>
  var app = new Vue({
	  el: '#app',
	  data: {
	    message: "${msg}"
	  }
	})
  </script>
</html>

WebContent/birdpage.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<title>主页-bootstrap(临时的)</title>
<!-- 新 Bootstrap 核心 CSS 文件 -->
<link
	href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css"
	rel="stylesheet">

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script
	src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="//unpkg.com/layui@2.6.5/dist/css/layui.css">
</head>

<body>
	<fieldset class="layui-elem-field" style="margin: 5%">
		<legend>乌鸦凤凰分页表</legend>
		<div class="layui-field-box" style="margin: 1%">
			<table class="layui-table" id="demo" lay-filter="test"></table>
		</div>
	</fieldset>
</body>
<script src="//unpkg.com/layui@2.6.5/dist/layui.js"></script>
<script type="text/javascript">
	
	layui.define(function(){
		
		var table = layui.table;
		var $ = layui.jquery;
		let tableData = [];
		
		//	表格渲染模板，开启分页
		table.render({
            elem: '#demo',
            cols: [[ //表头
                {field: 'id', title: 'ID', sort: true, fixed: 'left'},
                {field: 'type', title: '鸟类'}
            ]],
            page: true,
            limit: 10,
            limits: [5,10,15,20,50]
        });
		
		$.ajax({
			url: "${pageContext.request.contextPath}/birdpage",
			type: "post",
			data: {},
			contentType: "application/json;charset=UTF-8",
			dataType: "json",
			success: function(data){
				tableData = data;
				//	请求获得的数据作为表格静态数据，进行表格重载
				layui.table.reload('demo',{
                    data: tableData
                });
				
			}
		})
	})
	
</script>
</html>

WebContent/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<title>主页-bootstrap(临时的)</title>
<!-- 新 Bootstrap 核心 CSS 文件 -->
<link
	href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css"
	rel="stylesheet">

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script
	src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
	<div class="h1">第11章<span class="small">SpringMVC入门</span></div>
	<br>
	<div class="row clearfix">
			<div class="row">
				<div class="col-md-4">
					<div class="thumbnail">
						<div class="caption">
							<h3>控制器 firstController</h3>
							<p>演示 firstController -> first.jsp</p>
							<p>
								<a class="btn btn-primary" href="firstController">点我</a>
							</p>
						</div>
					</div>
				</div>

				<div class="col-md-4">
					<div class="thumbnail">
						<div class="caption">
							<h3>控制器 birdController</h3>
							<p>演示 birdController -> bird.jsp</p>
							<p>
								<a class="btn btn-primary" href="birdController">点我</a>
							</p>
						</div>
					</div>
				</div>
			</div>
	</div>
	</div>
</body>
</html>

WebContent/index2.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 
     "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Bootstrap 实例</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet"
	href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
<script
	src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
<script
	src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>

	<h2>主页（临时的）</h2>
	<div class="container">
		<a href="http://localhost:8080/chapter11/firstController">测试 firsController</a>
	</div>
	<div class="container">
		<a href="http://localhost:8080/chapter11/birdController">测试鸟</a>
	</div>
</body>
</html>